server:
  port: 80
  servlet:
    context-path: /text

country: shenyang

users:
  name: xueshihan

name: xueshihan

class1:
  name: xueshihan

# 使用${属性名}引用数据
baseDir: c:/windows
# 使用引号包裹的字符串,其中的转义字符可以生效
tempDir: ${baseDir}/win10

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql//
  username: root
  password: root666