customize:
  db:
    host: 192.168.3.55
    port: 5438
    name: iatc_trans_test
    username: root
    password: root
  redis:
    host: 192.168.3.55
    port: 6379
    password: Iatc@2022

server:
  servlet:
    context-path: /iatc
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
    disable-swagger-default-url: true
    version: 3.0.0
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${customize.db.host}:${customize.db.port}/${customize.db.name}
    username: ${customize.db.username}
    password: ${customize.db.password}
    driver-class-name: org.postgresql.Driver
    # druid ???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 10 #????????????????????????init????????getConnection?,??0
      maxActive: 200  #???????,??8
      minIdle: 10     #???????
      maxWait: 60000  #???????????,????????maxWait??,???????,?????????,??????????useUnfairLock???true???????
      timeBetweenEvictionRunsMillis: 60000 #1)Destroy????????????2)testWhileIdle?????(???testWhileIdle?????)
      minEvictableIdleTimeMillis: 300000   #?????????????(??)???? 1000L * 60L * 30L
      maxEvictableIdleTimeMillis: 900000   #?????????????(??)???? 1000L * 60L * 60L * 7
      validationQuery: SELECT 1 FROM t_user #???????????sql,????????????null???testOnBorrow?testOnReturn?testWhileIdle???????
      testWhileIdle: true #?????????,????????timeBetweenEvictionRunsMillis,??validationQuery????????,???true
      testOnBorrow: false #???????validationQuery????????????????????,??false.
      testOnReturn: false #???????validationQuery????????????????????,??false.
      poolPreparedStatements: true #????preparedStatement,???PSCache?PSCache???????????????,???oracle,?mysql??????
      #???PSCache???????0????0?? poolPreparedStatements???????true?
      #?Druid??????Oracle?PSCache??????????????????????????100
      maxOpenPreparedStatements: 20
      #????? minIdle ?????????????? minEvictableIdleTimeMillis????? keepAlive ??
      keepAlive: true

  redis:
    host: ${customize.redis.host}
    port: ${customize.redis.port}
    password: ${customize.redis.password}
    database: 0

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.iatc.entity
  configuration:
    map-underscore-to-camel-case: true
    # ??sql??????
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mqtt 需填写自己的
mqtt-client:
  hostUrl: ssl://mqtttest.iotwonderful.cn:8884
  clientId: consumer-12
  user-name: test_001
  password: NjBlNjY3ZWRlZ
  caCrt: ca.crt

  #    host-url: tcp://broker-cn.emqx.io:1883
  #    client-id: consumer-12
  #    user-name: emqx
  #    password: public

  # 连接超时 单位秒
  connect-timeout: 20
  #设置会话心跳时间 单位秒
  keepalive: 10
  # 完成时间，单位毫秒
  completion-timeout: 5000

# 雪花id
snowflake:
  datacenter-id: 0
  machine-id: 0

jwt:
  expire: 604800
  secret: JWT_TOKEN_SHIRO

logging:
  level:
    cn.iatc: debug
  config: classpath:log4j2.xml